name: CI/CD

on:
  push:
    branches:
      - master  # Change this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11  # Change this to match the JDK version you need

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x gradlew

    - name: Build and test
      run: ./gradlew test

    # Add more steps or jobs as needed for deployment, code analysis, etc.
